name: Release and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Get short SHA
        id: get_short_sha
        run: echo "::set-output name=short_sha::${GITHUB_SHA::7}"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_short_sha.outputs.short_sha }}
          tag_name: ${{ steps.get_short_sha.outputs.short_sha }}
          generate_release_notes: true
          files: build/libs/*.jar